management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8081
spring:
  application:
    name: Greet_Api
  boot:
    admin:
      client:
        url: http://localhost:8989/
