management:
  endpoints:
    web:
      exposure:
        include: '''*'''
server:
  port: 8081
spring:
  application:
    name: MicroService_GreetApi-2
  boot:
    admin:
      client:
        url: http://localhost:8989/
